# Project related configuration
devteam:
  # Name
  name: devteam
  # Version
  version: 3.2.1
  # Copyright year
  copyrightYear: 2020
  # Example demo switch
  demoEnabled: true
  # File path example (Windows configuration D:/devteam/uploadPath, Linux configuration /home/devteam/uploadPath)
  profile: D:/devteam/uploadPath
  # Get ip address switch
  addressEnabled: false
  # Verification code type math array calculation char character verification
  captchaType: math

# Development environment configuration
server:
  # The HTTP port of the server, the default is 8080
  port: 8080
  servlet:
    # Application access path
    context-path: /
  tomcat:
    # tomcat URI encoding
    uri-encoding: UTF-8
    # tomcat maximum number of threads, the default is 200
    max-threads: 800
    # Tomcat starts the initialization thread number, the default value is 25
    min-spare-threads: 30

# Log configuration
logging:
  level:
    com.devteam: debug
    org.springframework: warn

# Spring configuration
spring:
  # Resource Information
  messages:
    # Internationalized resource file path
    basename: i18n/messages
  profiles:
    active: druid
  # File Upload
  servlet:
     multipart:
       # Single file size
       max-file-size: 10MB
       # Set the total uploaded file size
       max-request-size: 20MB
  # Service module
  devtools:
    restart:
      # Hot deployment switch
      enabled: true
  # redis configuration
  redis:
    # Address
    host: localhost
    # Port, the default is 6379
    port: 6379
    # Password
    password:
    # Connection timeout
    timeout: 10s
    lettuce:
      pool:
        # The smallest idle connection in the connection pool
        min-idle: 0
        # The largest free connection in the connection pool
        max-idle: 8
        # The maximum number of database connections in the connection pool
        max-active: 8
        # #Connection pool maximum blocking waiting time (use a negative value to indicate no limit)
        max-wait: -1ms

# token configuration
token:
    # Token custom logo
    header: Authorization
    # Token key
    secret: abcdefghijklmnopqrstuvwxyz
    # Token validity period (default 30 minutes)
    expireTime: 30
  
# MyBatis configuration
mybatis:
    # Search for specified package alias
    typeAliasesPackage: com.devteam.**.domain
    # Configure mapper scanning and find all mapper.xml mapping files
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # Load the global configuration file
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper paging plugin
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger configuration
swagger:
  # Whether to open swagger
  enabled: true
  # Request prefix
  pathMapping: /dev-api

# Prevent XSS attacks
xss:
  # Filter switch
  enabled: true
  # Exclude links (multiple separated by commas)
  excludes: /system/notice/*
  # Match link
  urlPatterns: /system/*,/monitor/*,/tool/*